Dane do analizy: https://www.kaggle.com/datasets/mysarahmadbhat/lung-cancer

In [ ]:
#!/bin/bash
!kaggle datasets download mysarahmadbhat/lung-cancer

Dataset URL: https://www.kaggle.com/datasets/mysarahmadbhat/lung-cancer
License(s): CC0-1.0
Downloading lung-cancer.zip to /content
  0% 0.00/2.00k [00:00<?, ?B/s]
100% 2.00k/2.00k [00:00<00:00, 946kB/s]

In [ ]:
!unzip lung-cancer.zip

Archive:  lung-cancer.zip
  inflating: survey lung cancer.csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('survey lung cancer.csv')

In [ ]:
df.shape

(309, 16)

In [ ]:
df.to_excel('lung_cancer.xlsx')

In [ ]:
df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [ ]:
df = pd.get_dummies(df, columns=['GENDER'], drop_first=True)

In [ ]:
df

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER,GENDER_M
0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES,True
1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES,True
2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO,False
3,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO,True
4,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES,False
305,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES,True
306,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES,True
307,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES,True
308,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES,True

In [ ]:
X, y = df.drop('LUNG_CANCER', axis=1), df['LUNG_CANCER']

In [ ]:
X

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_M
0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,True
1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,True
2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,False
3,63,2,2,2,1,1,1,1,1,2,1,1,2,2,True
4,63,1,2,1,1,1,1,1,2,1,2,2,1,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,56,1,1,1,2,2,2,1,1,2,2,2,2,1,False
305,70,2,1,1,1,1,2,2,2,2,2,2,1,2,True
306,58,2,1,1,1,1,1,2,2,2,2,1,1,2,True
307,67,2,1,2,1,1,2,2,1,2,2,2,1,2,True
308,62,1,1,1,2,1,2,2,2,2,1,1,2,1,True

In [ ]:
from sklearn import linear_model

In [ ]:
clf  = linear_model.LogisticRegression(max_iter=1000)

In [ ]:
clf.fit(X, y)

LogisticRegression(max_iter=1000)

In [ ]:
clf.score(X, y)  # co to jest score dla modeli klasyfikacji

0.9320388349514563

In [ ]:
clf.predict(X)

array(['YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'NO', 'YES',
       'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'NO',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'YES', 'NO', 'NO',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'NO',
       'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'NO', 'YES', 'YES', 'NO',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'YES',
       'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'NO',
       'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES',
       'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES'], dtype=object)

In [ ]:
df['LUNG_CANCER']

0      YES
1      YES
2       NO
3       NO
4       NO
      ...
304    YES
305    YES
306    YES
307    YES
308    YES
Name: LUNG_CANCER, Length: 309, dtype: object

In [ ]:
(clf.predict(X) == df['LUNG_CANCER']).mean()

0.9320388349514563

# Predycje

In [ ]:
X.loc[0, :]

AGE                        69
SMOKING                     1
YELLOW_FINGERS              2
ANXIETY                     2
PEER_PRESSURE               1
CHRONIC DISEASE             1
FATIGUE                     2
ALLERGY                     1
WHEEZING                    2
ALCOHOL CONSUMING           2
COUGHING                    2
SHORTNESS OF BREATH         2
SWALLOWING DIFFICULTY       2
CHEST PAIN                  2
GENDER_M                 True
Name: 0, dtype: object

In [ ]:
clf.predict([X.loc[0, :]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['YES'], dtype=object)

In [ ]:
PATH = 'https://docs.google.com/spreadsheets/d/1rBjQiYpCopUaLAp6IiDEuXEwSr__ahSNtbr1J3jQ2cU/export?format=csv&gid=0'

In [ ]:
df_to_pred = pd.read_csv(PATH)

In [ ]:
df_to_pred

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_M
0,23,1,2,2,1,1,2,1,2,2,2,2,2,2,1
1,74,2,1,1,1,1,1,2,1,1,1,2,2,2,1
2,59,1,1,1,2,1,2,1,2,1,1,2,1,2,1
3,66,2,2,2,1,1,1,1,1,2,1,1,2,2,1
4,63,1,2,1,2,1,1,1,2,1,2,2,1,1,0
5,75,1,2,1,1,2,2,2,2,1,2,2,1,1,0
6,52,1,1,1,1,1,2,1,2,2,2,2,1,2,0
7,51,1,2,2,2,1,2,2,1,1,1,2,2,1,0
8,50,1,1,1,1,1,1,1,1,1,1,1,1,1,0
9,50,1,1,1,1,1,1,1,1,1,1,1,1,1,1
10,50,2,2,2,2,2,2,2,2,2,2,2,2,2,0
11,50,2,2,2,2,2,2,2,2,2,2,2,2,2,1
12,50,2,1,1,1,1,1,1,1,1,1,1,1,1,0
13,50,2,1,1,1,1,1,1,1,1,1,1,1,1,1
14,10,1,1,2,2,2,2,2,2,1,2,2,2,2,0
15,10,1,1,2,2,2,2,2,2,1,2,2,2,2,1

In [ ]:
clf.predict(df_to_pred)

array(['YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'NO',
       'YES', 'YES', 'NO', 'NO', 'YES', 'YES'], dtype=object)

In [ ]:
clf.predict_proba(df_to_pred)

array([[2.85556579e-02, 9.71444342e-01],
       [4.07744577e-01, 5.92255423e-01],
       [5.50496725e-01, 4.49503275e-01],
       [1.66846100e-01, 8.33153900e-01],
       [3.82838895e-01, 6.17161105e-01],
       [1.68123099e-02, 9.83187690e-01],
       [1.98482608e-01, 8.01517392e-01],
       [4.79385035e-02, 9.52061496e-01],
       [9.84555002e-01, 1.54449980e-02],
       [9.87522244e-01, 1.24777557e-02],
       [1.14486556e-04, 9.99885513e-01],
       [1.42134911e-04, 9.99857865e-01],
       [9.66284475e-01, 3.37155252e-02],
       [9.72664335e-01, 2.73356646e-02],
       [6.32648370e-03, 9.93673516e-01],
       [7.84255471e-03, 9.92157445e-01]])

In [ ]:
clf.coef_

array([[ 0.02438663,  0.79940471,  1.00919546,  0.71867218,  1.03589906,
         1.40482926,  1.49651223,  1.4330909 ,  0.81672394,  1.23420933,
         1.35453223,  0.09904357,  1.32681516,  0.50091519, -0.21634694]])

In [ ]:
clf.coef_.tolist()[0]

[0.02438662633443314,
 0.7994047097534478,
 1.0091954552131102,
 0.7186721780163814,
 1.035899061363278,
 1.4048292618249079,
 1.4965122343629595,
 1.433090898481731,
 0.8167239425786664,
 1.2342093345774345,
 1.3545322325181763,
 0.09904357120363484,
 1.326815160122854,
 0.5009151949218895,
 -0.21634694088904355]

In [ ]:
df_effects = pd.DataFrame({"zmienna": list(X.columns), "wspolczynnik": clf.coef_.tolist()[0]})

In [ ]:
df_effects

                  zmienna  wspolczynnik
0                     AGE      0.024387
1                 SMOKING      0.799405
2          YELLOW_FINGERS      1.009195
3                 ANXIETY      0.718672
4           PEER_PRESSURE      1.035899
5         CHRONIC DISEASE      1.404829
6                FATIGUE       1.496512
7                ALLERGY       1.433091
8                WHEEZING      0.816724
9       ALCOHOL CONSUMING      1.234209
10               COUGHING      1.354532
11    SHORTNESS OF BREATH      0.099044
12  SWALLOWING DIFFICULTY      1.326815
13             CHEST PAIN      0.500915
14               GENDER_M     -0.216347

# podział na train i na test

In [ ]:
from sklearn import model_selection

In [ ]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.4, random_state=4)

In [ ]:
clf.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
clf.score(X_train, y_train), clf.score(X_test, y_test)

(0.9081081081081082, 0.9596774193548387)

In [ ]:
df_effects = pd.DataFrame({"zmienna": list(X.columns), "wspolczynnik": clf.coef_.tolist()[0]})
df_effects

                  zmienna  wspolczynnik
0                     AGE      0.052670
1                 SMOKING      0.430171
2          YELLOW_FINGERS      0.886389
3                 ANXIETY      0.464416
4           PEER_PRESSURE      0.640773
5         CHRONIC DISEASE      1.215903
6                FATIGUE       1.342533
7                ALLERGY       1.338580
8                WHEEZING      0.746375
9       ALCOHOL CONSUMING      0.814212
10               COUGHING      0.790844
11    SHORTNESS OF BREATH      0.234008
12  SWALLOWING DIFFICULTY      1.082397
13             CHEST PAIN      0.601938
14               GENDER_M      0.037943